# Zoo Animal Classification 
TODO: 
- Fix NN
- Add EDA
- Discuss parameters and results of each 
- Other classification algorithms 
- Add logistic regression 

Dataset source: https://www.kaggle.com/uciml/zoo-animal-classification?select=class.csv

# Set Up

In [91]:
import csv
import numpy as np
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import confusion_matrix

# Set the randomizer seed so results are the same each time.
# np.random.seed(0)

In [97]:
# Load the data from ./zoo.csv
with open('zoo.csv', 'r') as f:
    animals = list(csv.reader(f))
animals = np.array(animals)

# Load the data from ./class.csv
with open('class.csv', 'r') as f:
    classes = list(csv.reader(f))
classes = np.array(classes)

# Split data into feature names, X (int), and Y(int)
features = animals[0][1:]
X = animals[1:,1:-1].astype(int)
Y = animals[1:,-1].astype(int)

# Retrieve class_type to class_name mapping
class_names = classes[1:,2]
class_types = classes[1:,0].astype(int)
class_map = {class_type: class_name for class_type, class_name in zip(class_types,class_names)}

# Set some variables to hold test, dev, and training data.
dev_data, dev_labels = X[60:], Y[60:]
train_data, train_labels = X[:60], Y[:60]

# Exploratory Data Analysis



# Utility Functions

In [98]:
def explore_errors(predictions, labels):
    incorrect_examples = []
    for i in range(len(predictions)):
        if predictions[i] != labels[i]:
            print("Predicted Label:", class_map[predictions[i]])
            print("True Label:\t", class_map[labels[i]])

# Models

### K-Nearest Neighbors Classifier

In [99]:
# Train a K Nearest Neighbors to classify mammal types 
def KNN_Classifier(num_neighbors):
    model = KNeighborsClassifier(num_neighbors)
    model.fit(train_data, train_labels)
    predictions = model.predict(test_data)
    score = model.score(dev_data, dev_labels)
    print("KNN Performance: ", score)
    print("KNN Confusion Matrix:\n")
    print(confusion_matrix(predictions, test_labels))
#     explore_errors(predictions, dev_labels)

KNN_Classifier(1)

KNN Performance:  0.8780487804878049
KNN Confusion Matrix:

[[5 0 1 0 0 0 0]
 [0 4 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 3 0 0 0]
 [0 0 1 0 1 0 0]
 [0 0 0 0 0 2 0]
 [0 0 0 0 0 0 3]]


### Random Forest

In [100]:
# Train a random forest to output the correct animal class 
def RandomForest_Classifier(num_trees):
    model = RandomForestClassifier(num_trees,max_depth=3)
    model.fit(train_data, train_labels)
    predictions = model.predict(test_data)
    score = model.score(dev_data, dev_labels)
    print("Random Forest Performance: ", score)
    print("Random Forest Confusion Matrix:\n")
    print(confusion_matrix(predictions, test_labels))
#     explore_errors(predictions, dev_labels)
    
RandomForest_Classifier(5)

Random Forest Performance:  0.8292682926829268
Random Forest Confusion Matrix:

[[5 0 0 0 0 0 0]
 [0 4 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 3 0 0 0]
 [0 0 1 0 1 0 0]
 [0 0 1 0 0 2 2]
 [0 0 0 0 0 0 1]]


### Neural Network

In [105]:
# Train a neural network to output the correct animal class 
def NeuralNetwork_Classifier():
    model = MLPClassifier(solver='lbfgs', activation='softmax', hidden_layer_sizes=(5,))
    model.fit(train_data, train_labels)
    predictions = model.predict(dev_data)
    score = model.score(dev_data, dev_labels)
    print("Random Forest Performance: ", score)
#     print("Random Forest Confusion Matrix:\n")
#     print(confusion_matrix(predictions, test_labels))
    #     explore_errors(predictions, dev_labels)

NeuralNetwork_Classifier()

KeyError: 'softmax'